spring:
  kafka:
    producer:
      bootstrap-server: localhost:9091,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 5
