spring:
  kafka:
    producer:
      bootstrap-server: ${KAFKA_BOOTSTRAP_SERVER_HOST}:${KAFKA_BOOTSTRAP_SERVER_PORT_1},${KAFKA_BOOTSTRAP_SERVER_HOST}:${KAFKA_BOOTSTRAP_SERVER_PORT_2}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone : ${EUREKA_URL}
    initial-instance-info-replication-interval-seconds: 5

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    org.springframework.kafka.transaction: DEBUG
    org.springframework.kafka.listener: DEBUG