eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    initial-instance-info-replication-interval-seconds: 5
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO
    org.springframework.kafka.transaction: DEBUG
    org.springframework.kafka.listener: DEBUG
